MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_NAME_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_PASSWORD_LENGTH = 100
ORDERING_SUBCCRIBE = ('-id',)
ORDERING_RECEPT = ('-pub_date',)
ORDERING_USER = ('username',)
MAX_LENGTH_NAME = 150
MAX_UNIT = 20
TAG_COLOR_CODE_LENGTH = 7
TAG_COLOR_CODE_REGEXP = r'\A#[0-9a-fA-F]{6}\Z'
MAX_LENGTH_NAME_SLUG = 150
USERNAME_FIELD = 'email'
USER = 'user'
ADMIN = 'admin'
ROLES = (
    (USER, 'Аут. пользователь'),
    (ADMIN, 'Администратор')
)
