# Generated by Django 3.2 on 2024-07-08 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240705_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.recipe')),
                ('base_link', models.URLField(blank=True, verbose_name='Прямая ссылка на рецепт')),
                ('short_link', models.CharField(max_length=20, verbose_name='Короткая ссылка на рецепт')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
